### PR TITLE
Include Rails 5.2 support

### PR DESCRIPTION
**Pull request by GeorgeKaraszi**
In response to: https://github.com/the-refinery/sparkpost_rails/issues/54

### CODE REVIEW

**Comment by GeorgeKaraszi** [comment]
@dgoerlich Is there anything else needed from me to get this moving?

**Comment by dgoerlich** [comment]
I can't merge this, as Travis fails because the gemfile.lock is out of date.  However, I've updated it on master, and pushed it - so I'm going to close this issue, as we accomplished the 5.2 support! :)

**Comment by sman591** [comment]
@dgoerlich Thanks! Is there a particular reason the gemspec is continually limited to "< 5.x", rather than a more generous `< 6.0` as proposed in this PR? Keeping it to the next major version would eliminate the need to continually bump this gemspec version (though it does sound like the next major release will be Rails 6.0 anyways)

**Comment by dgoerlich** [comment]
Yeah - it's to be conservative with expectations that any releases 5.3+ won't break the gem.  I don't expect they will, but I'd rather validate each and update the gem rather than fire it out there and hope. :)

**Pull request closed without merging**
