### PR TITLE
Support Rails 6.1

### PR DESCRIPTION
**Pull request by bradherman**

### CODE REVIEW

**Comment by pbhogan** [comment]
Gemspec should be `s.add_dependency 'rails', '>= 4.0', '< 6.2'` instead because, realistically, there would be no incompatibilities with patch releases.

**Comment by ROFISH** [comment]
Is all of Rails necessary even for this gem? Why not limit to ActiveMailer? For example: I do not want my gems including ActiveStorage as I have my own storage gem instead.

**Comment by bradherman** [comment]
> Gemspec should be `s.add_dependency 'rails', '>= 4.0', '< 6.2'` instead because, realistically, there would be no incompatibilities with patch releases.

Good call... Updated

**Comment by bradherman** [comment]
> Is all of Rails necessary even for this gem? Why not limit to ActiveMailer? For example: I do not want my gems including ActiveStorage as I have my own storage gem instead.

TBH I agree... Best to avoid Rails if possible... alas, I didn't create it, just trying to get it to work in my Rails proj, so might as well leave it for now

**Comment by buck3000** [comment]
What's the status of this PR? Looks good to merge, no?

**Comment by buck3000** [comment]
(not to be pushy, I am very appreciative of the gem but... rails 7 is just around the corner)

**Comment by olliebennett** [comment]
No issues for me when testing this PR - emails send fine and no apparent conflicts with Rails 6.1.

I'm using this in my `Gemfile` until it's merged;

```
# Use GitHub until https://github.com/the-refinery/sparkpost_rails/pull/79 is merged
gem 'sparkpost_rails', github: 'bradherman/sparkpost_rails', branch: 'rails-6.1-support'
```

**Pull request merged**
