### PR TITLE
Update dependency restriction to support rails 5.1

### PR DESCRIPTION
**Pull request by viamin**
Fixes https://github.com/the-refinery/sparkpost_rails/issues/41

Note specs are failing since the needed templates don't seem to be included in the repository. 
```
Failure/Error: format.text {render text: data[:text_part]}

      ActionView::MissingTemplate:
        Missing template mailer/test_email with {:locale=>[:en], :formats=>[:text], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}
```

### CODE REVIEW

**Comment by viamin** [comment]
Whoops, not sure why a0d5138 got added to this PR. Feel free to remove that (I can't figure out how)

**Comment by jlehman** [comment]
Any plans to finish this out and add support for Rails 5.1?

**Comment by sman591** [comment]
See https://github.com/the-refinery/sparkpost_rails/issues/41#issuecomment-329543176

**Comment by sman591** [comment]
Also @viamin if you wanted to remove that recent commit, you could run `git reset --hard HEAD^` and then `git push --force`

**Comment by viamin** [comment]
@sman591 Done - I've removed a0d5138.

**Pull request merged**
